### ISSUE TITLE
logrotate.d scripts filenames are quoted on the filesystem

### ISSUE THREAD

**Issue by letompouce** [bibliosansfrontieres/ideascube-deploy#34]
Introduced in https://github.com/bibliosansfrontieres/ideascube-deploy/commit/baed0ff38ca8d76be02c21670fbd0c38cdda806e#diff-71a9c4a441d8d6b6047075fc1da6d4acR14
```yaml
- name: Configure logrotate to handle our custom logs.
  template:
    src: "{{ item.src }}"
    dest: /etc/logrotate.d/"{{ item.dest }}"
```

This `/etc/logrotate.d/"{{ item.dest }}"` construction leads to filenames being "quoted":
```
# ls -1 /etc/logrotate.d/
"000-dateext-for-all"
"ansible-pull"
apport
apt
dpkg
"dpkg-list"
"hdw-info"
"nginx"
"pip-freeze"
rsyslog
tinc
ufw
unattended-upgrades
"uwsgi"
```

Note that it still works :sunglasses: : logs are correctly logrotated with the `dateext` setting applied.

Before we just fix this construction in [the `logs.yml`](https://github.com/bibliosansfrontieres/ideascube-deploy/blob/56bc4046dcfa81eeaa13e8bca963515dc7e92d2d/roles/setup_system/tasks/logs.yml#L14) task, we must fix the files on existing devices that have those files quoted. Otherwise they would end up with both files - with *and* without quotes.

This leads to the underlying question: how do we deal with quickfixes that should be performed once? Something like the database migrations? (a question that shall be addressed in an other issue, for sure)
